import { ReduxProvider } from '@/redux/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ReactQueryProvider from '@/components/Pages/Providers/ReactQueryProvider'
import { Suspense } from 'react'
import Loading from './loading'
import Navbar from '@/components/Layout/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center">
          <ReduxProvider>
            <Navbar />

            <div className="container p-4 md:px-0 mt-[60px]">
              <Suspense fallback={<Loading />}>
                <ReactQueryProvider>{children}</ReactQueryProvider>
              </Suspense>
            </div>
          </ReduxProvider>
        </main>
      </body>
    </html>
  )
}
